/**
 * TEMPORARY — AI-GENERATED — NOT HUMAN-MAINTAINED.
 *
 * Delete this whole directory when the stateless migration (#1128) closes.
 *
 * This file and `cases.json` were generated by an AI agent and have not been line-by-line reviewed
 * or adopted by a human maintainer. Treat findings as leads to verify, not as facts. Do not build
 * anything on top of it.
 *
 * It is scaffolding: it exists to prove the v1 (legacy sessionful) protocol surface is unchanged by
 * that migration. `tests/integration/suite.ts` remains the permanent, human-owned suite; do not
 * migrate coverage into here, and do not wire this into CI.
 *
 * See tests/e2e/README.md for how to run it and known instability.
 */
import { spawn } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

import { beforeAll, describe, expect, it } from 'vitest';

type McpcCase = {
    id: string;
    configs: string[];
    args: string[];
    /** jq filter run with `-e`. May reference `{{name}}` captures from earlier cases in the config. */
    assert?: string;
    /** Expect a non-zero mcpc exit, or a tool-level `isError: true` — see `respondsWithSomeError`. */
    expectError?: boolean;
    /** jq filters whose results are stored for `{{name}}` interpolation in later cases of the same config. */
    capture?: Record<string, string>;
    /**
     * Retry this probe while mcpc reports the task as still running — `tasks-result` errors until
     * the task reaches a terminal state.
     */
    pollWhileWorking?: boolean;
};

type McpcServerConfig = {
    /** Arguments for the spawned stdio server. Ignored when `url` is set. */
    args?: string[];
    /** Connect to an HTTP endpoint instead of spawning a stdio server. */
    url?: string;
    /** Env overrides for the spawned server. A `null` value removes the variable. */
    env?: Record<string, string | null>;
    /** Skip this configuration for `__all__` cases when it duplicates another configuration. */
    excludeFromAll?: boolean;
};

type McpcSuiteConfig = {
    configs: Record<string, McpcServerConfig>;
    cases: McpcCase[];
};

/** `"configs": ["__all__"]` runs a case against every configuration, so probes that apply
 * everywhere do not have to restate the config list each time one is added. */
const ALL_CONFIGS = '__all__';

const suite = JSON.parse(readFileSync(new URL('./cases.json', import.meta.url), 'utf8')) as McpcSuiteConfig;

/** mcpc is a devDependency, so it is only on PATH under `pnpm run`. Resolve it directly. */
const MCPC_BIN = resolve('node_modules/.bin/mcpc');

const SERVER_ENTRY = resolve('dist/stdio.js');

/** Base URL for HTTP configs, e.g. http://localhost:3001 with `pnpm run dev` running. */
const HTTP_BASE = process.env.E2E_HTTP_BASE;
const HTTP_BASE_TOKEN = '${E2E_HTTP_BASE}';

/** Run every configuration over HTTP against E2E_HTTP_BASE instead of spawning a stdio server. */
const HTTP_ONLY = process.env.E2E_HTTP_ONLY === '1';
if (HTTP_ONLY && !HTTP_BASE) throw new Error('E2E_HTTP_ONLY=1 requires E2E_HTTP_BASE.');

/** Stdio flags that are also query params. Anything else would become a silently ignored param. */
const HTTP_QUERY_FLAGS = new Set(['tools', 'actors', 'ui', 'payment', 'telemetry-enabled']);

/**
 * The URL that runs `config` over HTTP, or null when it cannot be expressed as one: configs that
 * vary the server's own env (`no-token`, `env-tools`, `env-ui-mode`) need a spawned server.
 */
function httpUrlFor(config: McpcServerConfig): string | null {
    if (config.url) return config.url;
    if (config.env) return null;
    const params = (config.args ?? []).map((arg) => arg.replace(/^--/, ''));
    if (params.some((param) => !HTTP_QUERY_FLAGS.has(param.split('=')[0]))) return null;
    return params.length > 0 ? `${HTTP_BASE_TOKEN}?${params.join('&')}` : HTTP_BASE_TOKEN;
}

/** HTTP configs need a running server, so they are skipped unless E2E_HTTP_BASE is set. */
function resolveActiveConfigs(): [string, McpcServerConfig][] {
    const entries = Object.entries(suite.configs);
    if (!HTTP_ONLY) {
        return entries.filter(([, config]) => !config.url?.includes(HTTP_BASE_TOKEN) || Boolean(HTTP_BASE));
    }

    const dropped: string[] = [];
    const active = entries.flatMap<[string, McpcServerConfig]>(([name, config]) => {
        const url = httpUrlFor(config);
        if (!url) {
            dropped.push(name);
            return [];
        }
        return [[name, { url, excludeFromAll: config.excludeFromAll }]];
    });
    if (dropped.length > 0) {
        console.warn(`E2E_HTTP_ONLY skips configs that need a spawned server: ${dropped.join(', ')}`);
    }
    return active;
}

const activeConfigs = resolveActiveConfigs();

/** The cases a configuration runs, in declaration order — capture chains depend on it. */
function casesFor(configName: string, config: McpcServerConfig) {
    return suite.cases.filter(
        (testCase) =>
            testCase.configs.includes(configName) || (testCase.configs.includes(ALL_CONFIGS) && !config.excludeFromAll),
    );
}

const DEFAULT_SERVER_ENV: Record<string, string | null> = {
    APIFY_TOKEN: '${APIFY_TOKEN}',
    NODE_EXTRA_CA_CERTS: '${NODE_EXTRA_CA_CERTS}',
};

/**
 * Per-probe wall clock. Kept well under the vitest test timeout so a wedged mcpc bridge reports a
 * named failure instead of being killed anonymously by the runner. See README, "Known instability":
 * mcpc can hang indefinitely on a `tools/call` or `prompts/get` protocol error, returning no output
 * at all, in which case the probe must fail loudly rather than stall the suite.
 */
const PROBE_TIMEOUT_MS = Number(process.env.E2E_PROBE_TIMEOUT_MS ?? 45_000);

type ProcessResult = {
    status: number | null;
    stdout: string;
    stderr: string;
};

function runProcess(
    command: string,
    args: string[],
    options: { input?: string; timeoutMs?: number } = {},
): Promise<ProcessResult> {
    return new Promise((resolvePromise, reject) => {
        const child = spawn(command, args, { stdio: 'pipe' });
        let stdout = '';
        let stderr = '';
        let hasTimedOut = false;

        child.stdout.setEncoding('utf8');
        child.stderr.setEncoding('utf8');
        child.stdout.on('data', (chunk: string) => {
            stdout += chunk;
        });
        child.stderr.on('data', (chunk: string) => {
            stderr += chunk;
        });

        const timeout = options.timeoutMs
            ? setTimeout(() => {
                  hasTimedOut = true;
                  child.kill('SIGKILL');
              }, options.timeoutMs)
            : undefined;

        child.on('error', reject);
        // mcpc bridges can keep inherited pipes open after the CLI exits, so `close` may never fire.
        child.on('exit', (status) => {
            if (timeout) clearTimeout(timeout);
            setImmediate(() => {
                child.stdout.destroy();
                child.stderr.destroy();
                if (hasTimedOut) {
                    reject(new Error(`Process produced no output within ${options.timeoutMs}ms.`));
                    return;
                }
                resolvePromise({ status, stdout, stderr });
            });
        });

        child.stdin.end(options.input);
    });
}

async function runMcpc(args: string[], options: { allowFailure?: boolean } = {}) {
    let result: ProcessResult;
    try {
        result = await runProcess(MCPC_BIN, args, { timeoutMs: PROBE_TIMEOUT_MS });
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(
            message.includes('produced no output')
                ? `mcpc ${args.join(' ')} produced no output within ${PROBE_TIMEOUT_MS}ms. ` +
                      'A hung bridge, not a server failure — see tests/e2e/README.md.'
                : `mcpc ${args.join(' ')} could not be run: ${message}`,
        );
    }
    if (!options.allowFailure && result.status !== 0) {
        throw new Error(`mcpc ${args.join(' ')} failed:\n${result.stderr}`);
    }

    return result;
}

/** `tasks-result` on a running task fails with this phrase, distinct from every other failure. */
const TASK_STILL_WORKING = 'is not completed yet';

/** ~40s of polling: generous next to the test Actor's usual multi-second run. */
const POLL_INTERVAL_MS = 2_000;
const POLL_MAX_ATTEMPTS = 20;

/**
 * True when `stdout` parses as a well-formed `CallToolResult` carrying `isError: true` — a valid
 * response the server chose to return, not a bridge or protocol failure.
 *
 * mcpc 0.2.x exits 0 for this case; mcpc 0.5.x exits 2, identically to a genuine JSON-RPC protocol
 * error (unknown tool, invalid arguments), which leaves stdout empty. Exit code alone can no longer
 * tell the two apart, so this checks payload shape instead — which keeps every case whose live
 * dependency (an external Actor, an external search backend) can legitimately be unreachable from
 * failing hard on that alone; its `assert` decides pass/fail from the actual payload instead.
 */
function isToolLevelErrorResponse(stdout: string): boolean {
    try {
        const parsed: unknown = JSON.parse(stdout);
        return (
            typeof parsed === 'object' &&
            parsed !== null &&
            (parsed as { isError?: unknown }).isError === true &&
            Array.isArray((parsed as { content?: unknown }).content)
        );
    } catch {
        return false;
    }
}

/** A non-zero mcpc exit that is not a valid tool-level error response: a protocol error, a bridge
 * crash, or mcpc's own CLI argument parsing rejecting the probe's arguments. */
function isGenuineFailure(result: { status: number | null; stdout: string }): boolean {
    return result.status !== 0 && !isToolLevelErrorResponse(result.stdout);
}

/**
 * True when the payload represents some kind of error — protocol-level (non-zero exit) or
 * tool-level (`isError: true`, whichever exit code this mcpc version happens to use for it).
 * `expectError` cases are checked against this, not raw exit code, so the same case definition
 * holds across mcpc's exit-code change between 0.2.x and 0.5.x.
 */
function respondsWithSomeError(result: { status: number | null; stdout: string }): boolean {
    return result.status !== 0 || isToolLevelErrorResponse(result.stdout);
}

/**
 * A deployed server rate-limits per token, which several configurations in flight trip on ordinary
 * methods (`tools/list`, `prompts/list`). Retryable, so it is not reported as a server failure.
 */
function isRateLimited(result: ProcessResult): boolean {
    return result.stderr.includes('Rate limit exceeded') || result.stdout.includes('Rate limit exceeded');
}

/**
 * Runs a probe, retrying while `pollWhileWorking` is set and mcpc reports the task still running,
 * or while the server is rate-limiting (any case, no opt-in). Any other genuine failure — including
 * running out of attempts — surfaces immediately as a normal unexpected-exit error.
 */
async function runMcpcCase(args: string[], testCase: McpcCase) {
    let result = await runMcpc(args, { allowFailure: true });

    let attempt = 1;
    while (
        isGenuineFailure(result) &&
        attempt < POLL_MAX_ATTEMPTS &&
        ((testCase.pollWhileWorking && result.stderr.includes(TASK_STILL_WORKING)) || isRateLimited(result))
    ) {
        await new Promise((resolvePromise) => {
            setTimeout(resolvePromise, POLL_INTERVAL_MS);
        });
        result = await runMcpc(args, { allowFailure: true });
        attempt += 1;
    }

    if (!testCase.expectError && isGenuineFailure(result)) {
        throw new Error(`mcpc ${args.join(' ')} failed:\n${result.stderr}`);
    }
    return result;
}

async function runJq(input: string, filter: string, options: { raw?: boolean } = {}) {
    return await runProcess('jq', [options.raw ? '-r' : '-e', filter], { input });
}

/** Builds the mcpc server entry written to the temporary config file. */
function buildServerEntry(config: McpcServerConfig) {
    if (config.url) {
        const url = config.url.replace(HTTP_BASE_TOKEN, HTTP_BASE ?? '');
        return { type: 'http', url, headers: { Authorization: 'Bearer ${APIFY_TOKEN}' } };
    }

    const env: Record<string, string> = {};
    for (const [key, value] of Object.entries({ ...DEFAULT_SERVER_ENV, ...config.env })) {
        if (value !== null) env[key] = value;
    }

    return { command: 'node', args: [SERVER_ENTRY, ...(config.args ?? [])], env };
}

/**
 * Removes mcpc's own `_mcpc` envelope. It carries the resolved APIFY_TOKEN in plaintext and the
 * absolute server path, so it must never reach an assertion or a failure message.
 */
async function stripMcpcEnvelope(payload: string) {
    const result = await runJq(payload, 'if type == "object" then del(._mcpc) else . end');
    // Non-JSON output (an mcpc crash, say) has no envelope to strip — assert against it as-is.
    return result.status === 0 ? result.stdout : payload;
}

function interpolate(value: string, captured: Record<string, string>) {
    return value.replace(/\{\{(\w+)\}\}/g, (_match, name: string) => {
        if (!(name in captured)) {
            throw new Error(`No captured value for {{${name}}}. Does an earlier case in this config capture it?`);
        }
        return captured[name];
    });
}

describe('v1 protocol', () => {
    beforeAll(async () => {
        if (!existsSync(MCPC_BIN)) throw new Error(`mcpc not found at ${MCPC_BIN}. Run \`pnpm install\`.`);
        if (!HTTP_ONLY && !existsSync(SERVER_ENTRY)) {
            throw new Error(`Server entry not found at ${SERVER_ENTRY}. Run \`pnpm run build\`.`);
        }
        const jq = await runProcess('jq', ['--version']);
        if (jq.status !== 0) throw new Error('`jq` is required by this suite but was not found on PATH.');
    });

    it.concurrent.each(activeConfigs)('%s', async (configName, config) => {
        const session = `@e2e-${configName}`;
        const captured: Record<string, string> = {};
        const configDirectory = mkdtempSync(join(tmpdir(), `actors-mcp-e2e-${configName}-`));
        const configPath = join(configDirectory, 'mcp.json');
        writeFileSync(configPath, JSON.stringify({ mcpServers: { server: buildServerEntry(config) } }));

        try {
            await runMcpc(['close', session], { allowFailure: true });
            await runMcpc(['connect', `${configPath}:server`, session]);

            for (const testCase of casesFor(configName, config)) {
                try {
                    const args = testCase.args.map((arg) => interpolate(arg, captured));
                    const result = await runMcpcCase(['--json', session, ...args], testCase);

                    // A protocol error writes its payload to stderr. A tool-level error uses stdout.
                    const payload = await stripMcpcEnvelope(result.stdout.trim() || result.stderr);

                    if (testCase.expectError && !respondsWithSomeError(result)) {
                        throw new Error(`Expected an error response, got a clean success:\n${payload}`);
                    }

                    if (testCase.assert) {
                        const assertion = await runJq(payload, interpolate(testCase.assert, captured));
                        expect(assertion.status, `Assertion failed: ${testCase.assert}\n${payload}`).toBe(0);
                    }

                    for (const [name, filter] of Object.entries(testCase.capture ?? {})) {
                        const value = (await runJq(payload, filter, { raw: true })).stdout.trim();
                        if (!value || value === 'null') {
                            throw new Error(`Capture "${name}" (${filter}) produced no value:\n${payload}`);
                        }
                        captured[name] = value;
                    }
                } catch (error) {
                    throw new Error(`Probe "${testCase.id}" failed.`, { cause: error });
                }
            }
        } finally {
            await runMcpc(['close', session], { allowFailure: true });
            rmSync(configDirectory, { recursive: true, force: true });
        }
    });
});
